import "@/app/reset.css";
import "@/app/styles/base.css";
import { sprinkles } from "@/app/styles/sprinkles.css";
import { FontVariable } from "@/app/styles/tokens";
import type { Metadata } from "next";
import { Bricolage_Grotesque, Inter } from "next/font/google";

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque" satisfies FontVariable,
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter" satisfies FontVariable,
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={[
        bricolageGrotesque.variable,
        inter.variable,
        sprinkles({
          text: "5",
        }),
      ].join(" ")}
    >
      <body
        className={sprinkles({
          background: "neutral-900",
          color: "neutral-0",
        })}
      >
        {children}
      </body>
    </html>
  );
}
